Проект ShareIt. Техническое задание. Часть 1
IgorBystrichenkoA/java-shareit pull request #1
Opened 2024-10-26 16:45 UTC by IgorBystrichenkoA

Добавлена логика работы с item и user

2024-10-26 17:04 UTC, IgorBystrichenkoA commented
Тесты поломаны. В тестах внутри запроса вместо id передается null
![image](https://github.com/user-attachments/assets/1a2ecd8e-d73e-4b35-ae80-27f080549162)

2024-10-26 19:22 UTC, EugeneLenkevich commented
> Тесты поломаны. В тестах внутри запроса вместо id передается null ![image](https://private-user-images.githubusercontent.com/163459108/380440024-1a2ecd8e-d73e-4b35-ae80-27f080549162.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5NzA3NzIsIm5iZiI6MTcyOTk3MDQ3MiwicGF0aCI6Ii8xNjM0NTkxMDgvMzgwNDQwMDI0LTFhMmVjZDhlLWQ3M2UtNGIzNS1hZTgwLTI3ZjA4MDU0OTE2Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNlQxOTIxMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MGUyOGE4YTk3OTg2M2FlZTg3YWRhZjQzYjc5ZWEyZDM1NDljMzBlODA5M2FmYTYyNmE1M2UyNjdlMDdhNWRiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.t5aFdo5xY_Ox7oRIn0W-n-TeQlQoPiPQjnClQ1cbSLY)

С этим лучше сразу к наставнику..

2024-10-26 19:32 UTC, EugeneLenkevich requested changes
Привет, Игорь! Спасибо за PR.

Все хорошо, единственное, давай проверим распределение ответственности по слоям.  У каждого слоя есть свои обязанности, если простыми словами то вот так
- контроллеры маршрутизируют сами запросы на наши сервисы
- сервисы оперируют понятиями предметной области, в них и содержится вся бизнес-логика 
- хранилище же занимается вопросами хранения, фильтрации и выборки данных

Если взять классическое определение то оно такое

> Первый слой абстракции — это слой доступа к данным. В задачи данного слоя входит абстрагирование от базы данных. SQL-запросы к базе данных, в которой и хранятся данные приложения, скрываются за фасадом, который использует бизнес-слой.
> 
> Второй слой абстракции — это слой бизнес-логики. Он содержит объекты предметной области, а также функции для работы с ними. Эти функции и реализуют данную бизнес-логику.
> 
> Третий слой абстракции — это слой взаимодействия с пользователем. Данный слой включает компоненты пользовательского интерфейса.

2024-10-26 19:32 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        itemCreateDto.setOwnerId(userId);
По своей сути контроллер только обрабатывает (маршрутизирует сервисам) запросы, а тут же в контроллере выполняется некоторая бизнес-логика, ее лучше перенести в сервис, иначе логика размазывается по нескольким классам :)

2024-10-26 19:32 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +@Data
`@Data`

С этой аннотацией надо поаккуратней. Она генерирует equals и hashCode на основании всех полей. 
Однако, сущность - это не просто объект, это представление строки таблицы базы данных, а строку таблицы однозначно определяет ее идентификатор, и потому, соотвественно, для сущностей equals и hashCode стоит определять на основе id (первичного ключа). 

Остальные поля, при этом, могут вообще быть разными, то есть могут существовать разные версии одного и того же объекта, но как это разруливатеся - это уже отдельная история.
 
Плюс еще некоторые поля могут быть ленивыми коллекциями и в момент обращения бдут генерироваться sql-запросы, которые и не нужны в данный момент

Т.е. лучше или переопределить руками или указать через аннотации как генерировать эти методы :)

2024-10-26 19:32 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/user/InMemoryUserRepository.java
> +        if (users.values().stream().anyMatch(u -> u.getEmail().equals(user.getEmail()))) {
Вот это очень похоже на бизнес логику. То есть сам поиск по email - вполне себе может быть методом хранилища, но вот выбрасывание исключения в случае если емейл не уникальный - это уже относится к нашей предметной области, выбрасывание исключения поднять бы в сервис :)

2024-10-27 03:21 UTC, EugeneLenkevich approved these changes
Ну да, в целом так, лог кстати тоже стоит в сервис опустить, в контроллере оставляем только вызов сервиса
В целом все гут, поехали дальше :)

2024-10-27 03:21 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/item/ItemController.java
>          log.info("Создан предмет: {}", item);
Лог тоже стоит в сервис перенести, он же описывает именно бизнес-сценарий :)

2024-10-27 07:36 UTC, merged